### ISSUE TITLE
Support for custom file extensions

### ISSUE THREAD

**Issue by apobekiaris** [tintoy/msbuild-project-tools-vscode#11]
Hi

My msbuild files have a .build extension and I would like to use this tool, is it possible to configure somehow ?

**Comment by tintoy** [comment]
Yes! There is a command called "change language for file extension" - just change the language to "MSBuild". It's Ctrl-K M from memory.

**Comment by tintoy** [comment]
Thanks, I'll add that to the README, it's not obvious.

**Comment by apobekiaris** [comment]
can you be a bit more specific I cannot locate this "change language for file extension" command. I tried to associate the .build with the msbuild language but I get

[Error - 11:15:18 PM] Unhandled exception in OnDidOpenTextDocument.
System.ArgumentException: Unexpected project file extension '.build'.
Parameter name: documentUri
   at MSBuildProjectTools.LanguageServer.Documents.ProjectDocument..ctor(Workspace workspace, Uri documentUri, ILogger logger) in D:\Development\github\tintoy\msbuild-project-tools\src\LanguageServer.Engine\Documents\ProjectDocument.cs:line 97
   at MSBuildProjectTools.LanguageServer.Documents.MasterProjectDocument..ctor(Workspace workspace, Uri documentUri, ILogger logger) in D:\Development\github\tintoy\msbuild-project-tools\src\LanguageServer.Engine\Documents\MasterProjectDocument.cs:line 46
   at MSBuildProjectTools.LanguageServer.Documents.Workspace.<>c__DisplayClass20_0.<GetProjectDocument>b__0(Uri _) in D:\Development\github\tintoy\msbuild-project-tools\src\LanguageServer.Engine\Documents\Workspace.cs:line 135
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MSBuildProjectTools.LanguageServer.Documents.Workspace.<GetProjectDocument>d__20.MoveNext() in D:\Development\github\tintoy\msbuild-project-tools\src\LanguageServer.Engine\Documents\Workspace.cs:line 130
--- End of stack trace from previous location where exception was thrown ---

**Comment by apobekiaris** [comment]
found the command also but when i click on the MSBuild language i get the same exception i posted before. VsCode 1.16 x64

**Comment by tintoy** [comment]
Ouch! Sorry, that's a bug. I'll fix that right away - give me 10 mins or so.

**Comment by tintoy** [comment]
Ok - I've tested the fix and it looks like it works correctly now; would you mind updating the extension to v0.2.4 and letting me know if this fixes your problem?

BTW, the docs [now show](https://github.com/tintoy/msbuild-project-tools-vscode/blob/master/README.md#file-extensions) how to change file associations.

**Comment by apobekiaris** [comment]
much better now many thnks!

wow first time in years I will actually be able to write msbuild scripts so productive. I wish this tool were available 10 years ago :). Great work!

**Comment by asking667788** [comment]
> Hi
> 
> My msbuild files have a .build extension and I would like to use this tool, is it possible to configure somehow ?

**Comment by tintoy** [comment]
Hi - you can set the language to “MSBuild” using these instructions:

https://vscode-docs.readthedocs.io/en/latest/languages/overview/#:~:text=In%20VS%20Code%2C%20we%20default,Palette%20for%20Select%20Language%20Mode.
